const countries = {
  // 22 Scheduled Languages
  "hi-IN": "Hindi",
  "kn-IN": "Kannada",
  "en-GM":"English",
  "as-IN": "Assamese",
  "bn-IN": "Bengali",
  "brx-IN": "Bodo",
  "doi-IN": "Dogri",
  "gu-IN": "Gujarati",
  
  
  "ks-IN": "Kashmiri",
  "kok-IN": "Konkani",
  "mai-IN": "Maithili",
  "ml-IN": "Malayalam",
  "mni-IN": "Manipuri (Meitei)",
  "mr-IN": "Marathi",
  "ne-IN": "Nepali",
  "or-IN": "Odia",
  "pa-IN": "Punjabi",
  "sa-IN": "Sanskrit",
  "sat-IN": "Santali",
  "sd-IN": "Sindhi",
  "ta-IN": "Tamil",
  "te-IN": "Telugu",
  "ur-IN": "Urdu",

  // Widely Spoken Non-Scheduled Languages
  "bho-IN": "Bhojpuri",
  "mag-IN": "Magahi",
  "raj-IN": "Rajasthani",
  "tcy-IN": "Tulu",
  "gon-IN": "Gondi",
  "bhb-IN": "Bhili",
  "kfa-IN": "Kodava (Coorgi)",
  "hne-IN": "Chhattisgarhi",
  "ang-IN": "Angika",
  "lmn-IN": "Lambadi (Banjara)",
  "awa-IN": "Awadhi",
  "bra-IN": "Braj Bhasha",
  "kha-IN": "Khasi",
  "gar-IN": "Garo",
  "mwr-IN": "Marwari",
  "pwr-IN": "Pawri",
  "thl-IN": "Tharu",
  "kokk-IN": "Kumaoni",
  "gvr-IN": "Gujari",
  "ho-IN": "Ho",
  "sck-IN": "Sadri",
  "lep-IN": "Lepcha",
  "mtr-IN": "Mewari",
  "unr-IN": "Mundari",
  "njo-IN": "Ao (Naga)",
  "lus-IN": "Mizo",
  "rkt-IN": "Rangpuri",
  "cdh-IN": "Chambeali"
};
